### ISSUE TITLE
"About" Section is Out of Date

### ISSUE THREAD

**Issue by jajanet** [brianstrauch/forkable-price-filter#3]
![Screen Shot 2022-07-20 at 2 51 07 PM](https://user-images.githubusercontent.com/31081135/180088541-ed121aae-ce33-4e59-824a-1d4a7ace6ff9.png)
Price was increased to $16 as part of #2 instead of $12.50, but the about section still says $12.50

**Comment by brianstrauch** [comment]
Thanks. The open source community wouldn't be same without your feedback 🥲
